data = [
    {'Name': 'Lenovo Yoga 7i (16)',
        'Price':88000,
        'Screen':{
            'size': 16,
            'ratio': '16:10',
            'resolution': '2560x1600',
            'brightness': 400,
            'touch': true,
            'type': 'IPS',
            'refresh': 60,
            'color-space': '100% sRGB',
        },
        'Convertible': true,
        'CPU':'Intel Core i7-1260P',
        'RAM': 16,
        'Storage': 1000,
        'GPU': 'Intel Iris Xe Graphics',
        'Battery': 71,
        'Weight': 1.98,
        'Width': 19.2,
        'Webcam': 1080,
        'IR': true,
        'Fingerprint': true,
        'Type_c_charging': true,
        'Variants':{1:{'Price': 70000,'CPU':'Intel Core i5-1240P', 'Storage': 512},
        }
        },
    {'Name': 'Lenovo Yoga 7i (14)',
        'Price':84000,
        'Screen':{
            'size': 14,
            'ratio': '16:10',
            'resolution': '2240x1400',
            'brightness': 300,
            'touch': true,
            'type': 'IPS',
            'refresh': 60,
            'color-space': '100% sRGB',
        },
        'Convertible': true,
        'CPU':'Intel Core i7-1255U',
        'RAM': 16,
        'Storage': 1000,
        'GPU': 'Intel Iris Xe Graphics',
        'Battery': 71,
        'Weight': 1.45,
        'Width': 17.35,
        'Webcam': 1080,
        'IR': true,
        'Fingerprint': true,
        'Type_c_charging': true,
        'Variants':{1:{'Price': 73000,'CPU':'Intel Core i5-1235U', 'Storage': 512},
        },
    },
    {'Name': 'Lenovo IdeaPad 5 pro',
        'Price':72000,
        'Screen':{
            'size': 16,
            'ratio': '16:10',
            'resolution': '2560x1600',
            'brightness': 300,
            'touch': false,
            'type': 'IPS',
            'refresh': 120,
            'color-space': '100% sRGB',
        },
        'Convertible': false,
        'CPU':'Ryzen 5 6600HS',
        'RAM': 16,
        'Storage': 512,
        'GPU': 'RTX 3050',
        'Battery': 75,
        'Weight': 1.95,
        'Width': 16.9,
        'Webcam': 1080,
        'IR': true,
        'Fingerprint': false,
        'Type_c_charging': false,
        'Variants':null,
    },
    ]   

folders = [['yoga7i16',9], ['yoga7i14',0], ['ideapad5pro',0]]